export default {
    // COLORS
    PRIMARY_COLOR: '#0171B9',
    SECONDARY_COLOR: '#a9a9a9',
    WHITE_COLOR: '#ffffff',
    BLACK_COLOR: '#000000',
    DARK_GREY_COLOR: '#404041',
    MID_GREY_COLOR: '#BCBDBF',
    LIGHT_GREY_COLOR: '#EBEBEB',
    SLATE_COLOR: '#262e33',
    BLUE_COLOR: '#2281b7',
    GREEN_COLOR: '#51B748',
    RED_COLOR: '#D31246',
    TAB_SELECTED_COLOR: '#00548A',
    TEXT_GREY_COLOR: "#2B2D30",
    TEXT_GREY_ITEM_COLOR: "#7C7C7D",
    BLACK_BACKGROUND: '#191919',


    FONT_SIZE_TINY: 10,
    FONT_SIZE_SMALLER: 12,
    FONT_SIZE_SMALL: 14,
    FONT_SIZE_MEDIUM: 16,
    FONT_SIZE_LARGE: 20,
    FONT_SIZE_EXTRA_LARGE: 30,
    FONT_SIZE_PAGE_HEADER: 24,
    FONT_WEIGHT_LIGHT: '200',
    FONT_WEIGHT_MEDIUM: '500',
    FONT_WEIGHT_BOLD: '700',
    BACKGROUND_COLOR_LIGHT: '#F3F3F3',
    BACKGROUND_COLOR_DARK: '#1C1F22',
    CONTAINER_PADDING: 20
  };